Repository apache/maven-wrapper, pull requests merged in 2025-08, with the labels that each got.

#348 Enable prevent branch protection rules
  .asf.yaml
Labels: maintenance

#145 [MWRAPPER-143] - The wrapperVersion property is not used in only-script mode
  maven-wrapper-plugin/src/it/projects/default/verify.groovy
  maven-wrapper-plugin/src/it/projects/mavenversion/verify.groovy
  maven-wrapper-plugin/src/it/projects/sh_type_only-script/verify.groovy
  maven-wrapper-plugin/src/it/projects/type_only-script/verify.groovy
  maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java
Labels: bug

#354 Refresh download page
  src/site/xdoc/download.xml.vm
Labels: maintenance

#355 Bump exec-maven-plugin to 3.5.1 in ITs
  maven-wrapper-plugin/src/it/projects/default/pom.xml
  maven-wrapper-plugin/src/it/projects/includeDebug/pom.xml
  maven-wrapper-plugin/src/it/projects/mavenversion-empty1/pom.xml
  maven-wrapper-plugin/src/it/projects/mavenversion-empty2/pom.xml
  maven-wrapper-plugin/src/it/projects/mavenversion/pom.xml
  maven-wrapper-plugin/src/it/projects/sh_type_only-script/pom.xml
  maven-wrapper-plugin/src/it/projects/sha256_distribution/pom.xml
  maven-wrapper-plugin/src/it/projects/sha256_type_only-script/pom.xml
  maven-wrapper-plugin/src/it/projects/sha256_wrapper/pom.xml
  maven-wrapper-plugin/src/it/projects/snapshot_distribution_test/pom.xml
  maven-wrapper-plugin/src/it/projects/test_mvnd/pom.xml
  maven-wrapper-plugin/src/it/projects/type_bin/pom.xml
  maven-wrapper-plugin/src/it/projects/type_only-script-fail/pom.xml
  maven-wrapper-plugin/src/it/projects/type_only-script/pom.xml
  maven-wrapper-plugin/src/it/projects/type_script/pom.xml
  maven-wrapper-plugin/src/it/projects/type_source/pom.xml
  maven-wrapper-plugin/src/it/projects/upgrade_with_existing_type/pom.xml
  pom.xml
Labels: dependencies
